[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"

[[services]]
name = "backend"
source = "/"
target = "backend"

[[services]]
name = "frontend"
source = "/frontend"
target = "frontend"
